server.port:
  8066

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.229:3306/bupt_hotel?useSSL=false&serverTimezone=UTC
    username: root
    password: P@ssw0ld

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai